//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCyclone.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_SysNotice : Db_SysMsg
    {
        public bool alert { get; set; }
        public string title { get; set; }
        public bool isRead { get; set; }
        public Nullable<System.DateTime> readTime { get; set; }
        public string readUser { get; set; }
        public string linkUrl { get; set; }
    }
}
