//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCyclone.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Db_WXCallBackNesMsgDetail
    {
        public int Id { get; set; }
        public string Db_WXCallBackNesMsgId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string picUrl { get; set; }
        public string url { get; set; }
    
        public virtual Db_WXCallBackNesMsg Db_WXCallBackNesMsg { get; set; }
    }
}
